class AllLists {
  static List<String> simpleAlphabetsAudios = [
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
  ];
  static List<String> simpleNumbersAudios = [
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
  ];
  static List<String> simpleUrduAudios = [
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
  ];
  static List<String> detailAlphabetsAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> detailNumbersAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
  ];
  static List<String> detailUrduAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
  ];
  static List<String> allAlphabetsDetail = [
    'A is for Allah, who made everything and loves us all.',
    'B is for Bismillah, saying "In the name of Allah" before good things we do.',
    'C is for Charity, sharing with those who need our help.',
    'D is for Dua, talking to Allah and asking Him for what we need.',
    'E is for Eid, a happy time when Muslims celebrate together.',
    "F is for Fasting, when we don't eat or drink during Ramadan to feel closer to Allah.",
    'G is for Grand Mosque (Masjid al-Haram), the sacred mosque in Mecca that surrounds the Kaaba.',
    'H is for Halal, which means things that are okay for us to have or do in Islam.',
    'I is for Iman, having strong faith and belief in Allah.',
    'J is for Jannat, the beautiful garden in paradise where good people go.',
    'K is for Kaaba, the special building Muslims face during prayers.',
    'L is for Laylat al-Qadr, a very special night in Ramadan when the Quran was first sent down.',
    "M is for Muhammad, who taught us about Islam and is Allah's last prophet.",
    'N is for Night Prayer (Tahajjud), a special prayer Muslims can do at night.',
    'O is for One God (Tawheed), believing in and worshiping only Allah.',
    'P is for Peace (Salam), a greeting and feeling of kindness and harmony.',
    'Q is for Quran, the holy book of Islam that teaches us how to live.',
    'R is for Ramadan, a month of fasting, prayer, and reflection.',
    'S is for Salah, the prayers Muslims perform every day.',
    'T is for Tawakkul, trusting Allah and knowing He will take care of us.',
    'U is for Ummah, the worldwide community of Muslims who care for each other.',
    'V is for Virtue (Ihsan), striving to be the best version of ourselves in worship and behavior.',
    'W is for Wudu, washing before prayers to be clean and ready to worship.',
    'X is for Excellence in character, being kind, honest, and respectful like our Prophet Muhammad.',
    'Y is for Yaqeen: Unwavering faith and belief in Allah, His attributes, and His promises.',
    'Z is for Zakat, giving to those in need to help make the world a better place.',
  ];
  static List<String> allNumbersDetail = [
    "There is one bus, zooming to school, with seats so big and windows so cool.",
    'There are two birds, soaring through the sky, flapping their wings way up high.',
    'There are three kittens, frolicking with glee, tumbling and rolling, so happy and free.',
    'There are four kites, dancing in the breeze, colorful tails swirling with ease.',
    'There are five balloons, bobbing in the air, colors so bright, here and there.',
    'There are six puppies, chasing each other round, yipping and pawing off the ground.',
    "There are seven fish, gliding under the pond's glassy sheet, flicking their fins, swift and neat.",
    "There are eight clouds, fluffy and white, drifting across the sky, light and bright.",
    'There are nine stars, twinkling so fine, glittering like treasures in the nighttime shine.',
    'There are ten pencils, lying in a line, colors galore, designed to define.',
    'There are eleven butterflies, fluttering so high, wings like rainbows in the sky.',
    'There are twelve strawberries, juicy and sweet, red and ripe, a treat to eat.',
    'There are thirteen ladybugs, crawling leaf to leaf, tiny and round, beyond belief.',
    'There are fourteen flowers, bursting with hues, spreading their beauty, perfuming the dews.',
    'There are fifteen apples, green and bright, dangling on branches, a delightful sight.',
    'There are sixteen school bags, lined up for sale, colors and pockets, rugged and frail.',
    'There are seventeen balloons, drifting to the fair, rising above, light as air.',
    'There are eighteen coins, glittering gold, treasures of stories, old and untold.',
    'There are nineteen chairs, waiting in a row, sturdy and strong, for the school day’s flow.',
    'There are twenty biscuits, golden and round, stacked up high, just waiting to be found.',
  ];
  static List<String> allUrduDetail = [
    'ا سے اللہ، جو ہر چیز کا پیدا کرنے والا ہے اور ہماری محبت کرتا ہے۔',
    'ب سے برکت، جو اللہ کی نعمت اور رحمت کا ظاہری نشان ہے۔',
    'پ سے پیغمبر، جن کو اللہ نے بشارت دی اور ہدایت کی۔',
    'ت سے توبہ، جو گناہوں سے رجوع کا راستہ ہے۔',
    'ٹ سے ٹھکانہ، جو ہر چیز کا مقصود اور منزل ہے۔',
    'ث سے ثواب، جو نیکیوں کا انجام ہے اور اعمال کی بدلہ دینے والا ہے۔',
    'ج سے جنت، جو مومنین کی مقصود اور حقیقی منزل ہے۔',
    'چ سے چراغ، جو روشنی اور ہدایت کا سورج ہے۔',
    'ح سے حق، جو سچائی اور عدل کا نام ہے۔',
    'خ سے خیرات، جو دیگروں کی خوشی اور بہتری کے لیے کرنا۔',
    "د سے دین، جو اسلام کا بنیادی رکن ہے اور اللہ کی راہنمائی کا ذریعہ ہے۔",
    'ڈ سے ڈر، جو اللہ سے خوف اور ہدایت کا ذریعہ ہے۔',
    'ذ سے ذکر، جو اللہ کی یاد دلانے والا اور سکون اور برکت کا ذریعہ ہے۔',
    'ر سے رحمت، جو اللہ کی بے پایاں مہربانی ہے۔',
    'ز سے زندگی، جو اللہ کی قدرت کا مظہر ہے اور انسان کی آخرت کی خبر دیتی ہے۔',
    'ژ سے ژالہ باری، جو اللہ کی قدرت کا مظاہر ہے اور فطرت کی خوبصورتی کو دکھاتی ہے۔',
    "س سے سکون، جو دل کی تسکین اور چین کا سرچشمہ ہے۔",
    'ش سے شریعت، جو اللہ کی ہدایات اور احکامات کا مجموعہ ہے۔',
    'ص سے صدقہ، جو دینی اور دنیاوی بھلائی کا ذریعہ ہے۔',
    'ض سے ضیاء، جو روشنی اور نور کا ذریعہ ہے۔',
    'ط سے طاعت، جو اللہ کی رضا اور محبت کا ذریعہ ہے۔',
    'ظ سے ظلم، جو بے عدلی اور ناانصافی کا ذریعہ ہے۔',
    'ع سے علم، جو روشنی اور فہم کا سرچشمہ ہے۔',
    'غ سے غفران، جو گناہوں کی معافی اور توبہ کا ذریعہ ہے۔',
    'ف سے فراہمی، جو روزی اور نعمتوں کا وسیلہ ہے۔',
    'ق سے قرآن، جو اللہ کی کلام پاک اور ہدایت کی آخری کتاب ہے۔',
    'ک سے کرم، جو احسان اور نیکی کا ذریعہ ہے۔',
    'گ سے گناہ، جو اللہ کی نافرمانی اور ناراضگی کا سبب ہے۔',
    'ل سے لطفِ عبادت، جو ایمان کی لذت اور قرب الٰہی کا ذریعہ ہے۔',
    'م سے مؤمن، جو اللہ اور اس کے رسول پر ایمان رکھنے والا ہے۔',
    'ن سے نماز، جو مسلمانوں پر فرض عبادت اور اللہ سے رابطہ ہے۔',
    'و سے ولایت، جو اللہ کی طرف سے کسی بندے کو خاص مقام عطا کرنا ہے۔',
    'ہ سے ہدایت، جو اللہ کی طرف سے سیدھا راستہ اور رستگاری کا ذریعہ ہے۔',
    'ھ سے ھدایت یافتہ، جو اللہ کی رہنمائی پر چلنے والا ہے۔',
    'ء سے ءاخرت، جو آخرت کا ذریعہ اور موت کا انجام ہے۔',
    'ی سے یقین، جو اللہ پر کامل اعتماد اور ایمان کی بنیاد ہے۔',
  ];
  static List<String> alphabetsImages = [
    'assets/images/Alphabets/A.png',
    'assets/images/Alphabets/B.png',
    'assets/images/Alphabets/C.png',
    'assets/images/Alphabets/D.png',
    'assets/images/Alphabets/E.png',
    'assets/images/Alphabets/F.png',
    'assets/images/Alphabets/G.png',
    'assets/images/Alphabets/H.png',
    'assets/images/Alphabets/I.png',
    'assets/images/Alphabets/J.png',
    'assets/images/Alphabets/K.png',
    'assets/images/Alphabets/L.png',
    'assets/images/Alphabets/M.png',
    'assets/images/Alphabets/N.png',
    'assets/images/Alphabets/O.png',
    'assets/images/Alphabets/P.png',
    'assets/images/Alphabets/Q.png',
    'assets/images/Alphabets/R.png',
    'assets/images/Alphabets/S.png',
    'assets/images/Alphabets/T.png',
    'assets/images/Alphabets/U.png',
    'assets/images/Alphabets/V.png',
    'assets/images/Alphabets/W.png',
    'assets/images/Alphabets/X.png',
    'assets/images/Alphabets/Y.png',
    'assets/images/Alphabets/Z.png',
  ];
  static List<String> numbersImages = [
    'assets/images/Alphabets/A.png',
    'assets/images/Alphabets/B.png',
    'assets/images/Alphabets/C.png',
    'assets/images/Alphabets/D.png',
    'assets/images/Alphabets/E.png',
    'assets/images/Alphabets/F.png',
    'assets/images/Alphabets/G.png',
    'assets/images/Alphabets/H.png',
    'assets/images/Alphabets/I.png',
    'assets/images/Alphabets/J.png',
    'assets/images/Alphabets/K.png',
    'assets/images/Alphabets/L.png',
    'assets/images/Alphabets/M.png',
    'assets/images/Alphabets/N.png',
    'assets/images/Alphabets/O.png',
    'assets/images/Alphabets/P.png',
    'assets/images/Alphabets/Q.png',
    'assets/images/Alphabets/R.png',
    'assets/images/Alphabets/S.png',
    'assets/images/Alphabets/T.png',
  ];
  static List<String> urduImages = [
    'assets/images/Urdu/ا.png',
    'assets/images/Urdu/ب.png',
    'assets/images/Urdu/پ.png',
    'assets/images/Urdu/ت.png',
    'assets/images/Urdu/ٹ.png',
    'assets/images/Urdu/ث.png',
    'assets/images/Urdu/ج.png',
    'assets/images/Urdu/چ.png',
    'assets/images/Urdu/ح.png',
    'assets/images/Urdu/خ.png',
    'assets/images/Urdu/د.png',
    'assets/images/Urdu/ڈ.png',
    'assets/images/Urdu/ذ.png',
    'assets/images/Urdu/ر.png',
    'assets/images/Urdu/ز.png',
    'assets/images/Urdu/ژ.png',
    'assets/images/Urdu/س.png',
    'assets/images/Urdu/ش.png',
    'assets/images/Urdu/ص.png',
    'assets/images/Urdu/ض.png',
    'assets/images/Urdu/ط.png',
    'assets/images/Urdu/ظ.png',
    'assets/images/Urdu/ع.png',
    'assets/images/Urdu/غ.png',
    'assets/images/Urdu/ف.png',
    'assets/images/Urdu/ق.png',
    'assets/images/Urdu/ک.png',
    'assets/images/Urdu/گ.png',
    'assets/images/Urdu/ل.png',
    'assets/images/Urdu/م.png',
    'assets/images/Urdu/ن.png',
    'assets/images/Urdu/و.png',
    'assets/images/Urdu/ہ.png',
    'assets/images/Urdu/ھ.png',
    'assets/images/Urdu/ء.png',
    'assets/images/Urdu/ی.png',
  ];
  static List<String> urduLetters = [
    'assets/images/Urdu_Letters/ا.png',
    'assets/images/Urdu_Letters/ب.png',
    'assets/images/Urdu_Letters/پ.png',
    'assets/images/Urdu_Letters/ت.png',
    'assets/images/Urdu_Letters/ٹ.png',
    'assets/images/Urdu_Letters/ث.png',
    'assets/images/Urdu_Letters/ج.png',
    'assets/images/Urdu_Letters/چ.png',
    'assets/images/Urdu_Letters/ح.png',
    'assets/images/Urdu_Letters/خ.png',
    'assets/images/Urdu_Letters/د.png',
    'assets/images/Urdu_Letters/ڈ.png',
    'assets/images/Urdu_Letters/ذ.png',
    'assets/images/Urdu_Letters/ر.png',
    'assets/images/Urdu_Letters/ز.png',
    'assets/images/Urdu_Letters/ژ.png',
    'assets/images/Urdu_Letters/س.png',
    'assets/images/Urdu_Letters/ش.png',
    'assets/images/Urdu_Letters/ص.png',
    'assets/images/Urdu_Letters/ض.png',
    'assets/images/Urdu_Letters/ط.png',
    'assets/images/Urdu_Letters/ظ.png',
    'assets/images/Urdu_Letters/ع.png',
    'assets/images/Urdu_Letters/غ.png',
    'assets/images/Urdu_Letters/ف.png',
    'assets/images/Urdu_Letters/ق.png',
    'assets/images/Urdu_Letters/ک.png',
    'assets/images/Urdu_Letters/گ.png',
    'assets/images/Urdu_Letters/ل.png',
    'assets/images/Urdu_Letters/م.png',
    'assets/images/Urdu_Letters/ن.png',
    'assets/images/Urdu_Letters/و.png',
    'assets/images/Urdu_Letters/ہ.png',
    'assets/images/Urdu_Letters/ھ.png',
    'assets/images/Urdu_Letters/ء.png',
    'assets/images/Urdu_Letters/ی.png',
  ];
  static List<String> shapesImages = [
    'assets/images/Shapes/Circle.png',
    'assets/images/Shapes/Triangle.png',
    'assets/images/Shapes/Square.png',
    'assets/images/Shapes/Pentagon.png',
    'assets/images/Shapes/Hexagon.png',
    'assets/images/Shapes/Polygon.png',
    'assets/images/Shapes/Cone.png',
    'assets/images/Shapes/Diamond.png',
    'assets/images/Shapes/Oval.png',
    'assets/images/Shapes/Parallelogram.png',
    'assets/images/Shapes/Rectangle.png',
    'assets/images/Shapes/Trapezium.png',
  ];
  static List<String> shapesNames = [
    'Circle',
    'Triangle',
    'Square',
    'Pentagon',
    'Hexagon',
    'Octagon',
    'Cone',
    'Diamond',
    'Oval',
    'Parallelogram',
    'Rectangle',
    'Trapezium'
  ];
  static List<String> shapesDetail = [
    'A circle is a round shape, like a cookie or a clock, where every point on the edge is the same distance from the middle.',
    'A triangle is a shape with three straight sides and three corners, like a slice of pizza.',
    'A square is a shape with four equal sides and four corners, like a game board or a window.',
    'A pentagon is a shape with five sides and five corners, like a starfish when you draw it with straight lines.',
    'A hexagon is a shape with six sides and six corners, like the cells in a honeycomb.',
    'An octagon is a shape with eight straight sides and eight corners, like a big juicy pizza sliced into eight pieces.',
    'A cone is a fun shape that looks like an ice cream cone! It has a round, flat base, and it comes to a point at the top.',
    'A diamond shape looks like a square standing on one of its corners, with four sides and pointy edges, just like a kite!',
    "An oval is like a squished circle! It's rounded like a ball but stretched out like a big, smooth egg. Think of how some fruits like grapes or plums might look if you gave them a gentle squeeze!",
    "A parallelogram is a fun shape with opposite sides that are equal in length and never meet. It's like a squished rectangle, and you can find it in things like windows or the pages of a book!",
    "A rectangle is like a yummy chocolate bar! It has two long sides and two short sides, and all the corners are right angles, just like the corners of a book.",
    "A trapezium is a four-sided shape that's like a wonky rectangle! It's like a slice of cake with one side longer than the other, and it's used in cool signs and building designs.",
  ];
  static List<String> shapesAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> animalsImages = [
    'assets/images/animals/Tiger.png',
    'assets/images/animals/lion.png',
    'assets/images/animals/Deer.png',
    'assets/images/animals/Elephant.png',
    'assets/images/animals/Panda.png',
    'assets/images/animals/Zebra.png',
    'assets/images/animals/Camel.png',
    'assets/images/animals/Dog.png',
    'assets/images/animals/Rabbit.png',
    'assets/images/animals/Sheep.png',
    'assets/images/animals/Squirrel.png',
    'assets/images/animals/Turtle.png',
  ];
  static List<String> animalNames = [
    'Tiger',
    'Lion',
    'Deer',
    'Elephant',
    'Panda',
    'Zebra',
    'Camel',
    'Dog',
    'Rabbit',
    'Sheep',
    'Squirrel',
    'Turtle',
  ];
  static List<String> animalDetail = [
    'Tigers are large, orange cats with black stripes, and they love to run and play in the jungle!',
    "Lions are majestic animals with golden fur and a big, bushy mane around their necks, and they're known as the kings of the jungle!",
    'The swamp deer, also known as the embarrassing, is a deer with big, branching antlers found in wetlands, and its impressive antlers can have up to twelve points!',
    'Elephants are the largest land animals, with long trunks they use to drink water and grab food. They have big ears that help them stay cool, and they love taking baths in rivers!',
    'Giant pandas are black and white bears who love to munch on yummy bamboo all day long!',
    'Zebras are like horses wearing fancy black and white stripes, and they live in big groups called herds, playing and running together on the grassy plains of Africa!',
    "Camels are amazing animals with humps on their backs that store fat, helping them survive in hot deserts by providing energy when food and water are scarce.",
    "Dogs are friendly and loyal companions that come in various shapes, sizes, and breeds, offering endless love and joy to families around the world.",
    "Rabbits are cute and furry animals known for their long ears and quick hops, enjoying nibbling on carrots and exploring their surroundings with boundless curiosity.",
    "Sheep are gentle creatures with fluffy coats that provide wool for clothing and are often found grazing peacefully in fields, forming close-knit communities within their flocks.",
    "Squirrels are agile little creatures with bushy tails, known for their acrobatic antics as they scamper through trees and parks, gathering nuts for the winter ahead.",
    "Turtles are fascinating reptiles with protective shells that carry their homes on their backs, moving slowly but surely on land and gracefully in water, symbolizing longevity and resilience in nature.",
  ];
  static List<String> animalAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> treesImages = [
    'assets/images/Trees/Oak Tree.png',
    'assets/images/Trees/Maple Tree.png',
    'assets/images/Trees/Pine Tree.png',
    'assets/images/Trees/Cherry Tree.png',
    'assets/images/Trees/Palm Tree.png',
    'assets/images/Trees/Apple tree.png',
    'assets/images/Trees/Birch tree.png',
    'assets/images/Trees/Fig tree.png',
    'assets/images/Trees/Mango tree.png',
    'assets/images/Trees/Orange tree.png',
    'assets/images/Trees/Poplar tree.png',
    'assets/images/Trees/Willow tree.png',
  ];
  static List<String> treesNames = [
    'Oak Tree',
    'Maple Tree',
    'Pine Tree',
    'Cherry Tree',
    'Palm Tree',
    'Apple Tree',
    'Birch Tree',
    'Fig Tree',
    'Mango Tree',
    'Orange Tree',
    'Poplar Tree',
    'Willow Tree',
  ];
  static List<String> treesDetail = [
    'Oak trees are like big, friendly giants with leaves that turn golden in the fall. They provide homes for birds and squirrels and give us shade to play under on sunny days!',
    'Maple trees are beautiful trees with leaves that turn vibrant shades of red, orange, and yellow in the fall. They produce sweet sap that is used to make maple syrup, a delicious treat!',
    "Pine trees are like nature's Christmas trees, with long needles and cones. They smell fresh and wonderful, especially in the forest during a crisp morning walk!",
    'Cherry trees are lovely trees with delicate pink or white blossoms in the spring, followed by juicy cherries in the summer. They bring joy with their beautiful flowers and delicious fruit!',
    "Palm trees are tall, slender trees with big, fan-shaped leaves and coconuts growing on top. They make you feel like you're on a tropical island, swaying gently in the warm breeze!",
    "Apple trees are like nature's candy store, with branches filled with juicy apples just waiting to be picked and enjoyed!",
    "Birch trees are tall and slender with distinctive white bark, known for their delicate leaves that flutter in the breeze and their association with new beginnings and renewal in forests across the world.",
    "Fig trees are like nature's candy store, with big leaves for shade and yummy fruits that taste like sweet treats, inviting kids and animals to enjoy their delicious bounty in sunny places.",
    "Mango trees are like big treasure chests in the garden, full of juicy fruits that taste like a tropical adventure, waiting for kids to climb up and discover their delicious treasures, making every bite a sweet, sunny delight!",
    "Orange trees are like nature's gift machines, always giving juicy oranges with a burst of sweet and tangy flavor, just perfect for kids to pick and enjoy, turning every day into a citrusy celebration!",
    "Poplar trees are like nature's towers, their towering height and rustling leaves providing a playground for kids' imaginations to soar, turning each climb into a leafy adventure!",
    "Willow trees are like nature's storytellers, their branches waving like magic wands, inviting kids to sit and dream beneath their leafy canopy, where every rustle holds a secret tale waiting to be discovered",
  ];
  static List<String> treesAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> colorsImages = [
    'assets/images/Colors/green 1.png',
    'assets/images/Colors/yellow 1.png',
    'assets/images/Colors/orange 1.png',
    'assets/images/Colors/pink 1.png',
    'assets/images/Colors/blue 1.png',
    'assets/images/Colors/Red 1.png',
    'assets/images/Colors/grey 1.png',
    'assets/images/Colors/brown 1.png',
    'assets/images/Colors/purple 1.png',
    'assets/images/Colors/magneto 1.png',
    'assets/images/Colors/white 1.png',
    'assets/images/Colors/black 1.png',
  ];
  static List<String> colorsNames = [
    'Green',
    'Yellow',
    'Orange',
    'Pink',
    'Blue',
    'Red',
    'Grey',
    'Brown',
    'Purple',
    'Magneto',
    'White',
    'Black',
  ];
  static List<String> colorsDetail = [
    "Green is the color of fresh grass, cool cucumbers, and friendly frogs hopping around in the pond! It's a happy color that reminds us of nature and outdoor adventures!",
    "Yellow is the color of sunshine, bananas, and happy faces! It's a bright and cheerful color that makes you feel warm and joyful, like a sunny day at the beach!",
    "Orange is the color of cheerful pumpkins, juicy oranges, and friendly goldfish swimming in the pond. It's a bright and happy color that makes you feel warm and full of energy!",
    "Pink is the color of cotton candy, pretty flowers, and fluffy kittens! It's a soft and gentle color that brings feelings of sweetness and happiness, like a warm hug from a friend!",
    "Blue is the color of the sky on a sunny day, the ocean waves, and the feathers of a beautiful peacock. It's a cool and calming color that makes you feel peaceful and happy!",
    "Red is the color of juicy apples, speedy race cars, and friendly ladybugs crawling on your hand. It's a bright and exciting color that makes you feel full of energy and ready for fun adventures!",
    "Grey is the color of friendly elephants, clever dolphins, and the clouds floating in the sky. It's a soft and gentle color that makes you feel calm and cozy, like wrapping yourself in a warm blanket!",
    "Brown is the color of chocolate, teddy bears, and the dirt where plants grow. It's a cozy color that makes you feel warm and safe, like being wrapped in a hug!",
    "Purple is the color of magical wizards and beautiful flowers, like the ones in fairy tales!",
    "Magneto is often associated with the color red and purple, reflecting his power and regal presence as a mutant leader.",
    "White is the color of clouds in the sky, fluffy bunnies hopping around, and paper where you can draw colorful pictures! It's a clean and bright color that makes you feel happy and full of possibilities!",
    "Black is the color of the night sky, where stars sparkle like glitter, and it's the color of cool bats flying around! It's a mysterious and exciting color that makes you feel like you're on a thrilling adventure!",
  ];
  static List<String> colorsAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> vegetablesImages = [
    'assets/images/Vegetables/carrot.png',
    'assets/images/Vegetables/tomato.png',
    'assets/images/Vegetables/potato.png',
    'assets/images/Vegetables/broccoli.png',
    'assets/images/Vegetables/radish.png',
    'assets/images/Vegetables/spinach.png',
    'assets/images/Vegetables/Chilli.png',
    'assets/images/Vegetables/Cucumber.png',
    'assets/images/Vegetables/Eggplant.png',
    'assets/images/Vegetables/Garlic.png',
    'assets/images/Vegetables/Onion.png',
    'assets/images/Vegetables/Turnip.png',
  ];
  static List<String> vegetablesNames = [
    'Carrot',
    'Tomato',
    'Potato',
    'Cauliflower',
    'Radish',
    'Spinach',
    'Chilli',
    'Cucumber',
    'EggPlant',
    'Garlic',
    'Onion',
    'Turnip',
  ];
  static List<String> vegetablesDetail = [
    "Carrots are like crunchy, orange sticks that give you super eyesight and make you feel strong! They're delicious to eat raw or cooked, and they're the favorite snack of rabbits hopping around in the garden!",
    "Tomatoes are juicy, red fruits that grow on vines and are used in salads, sandwiches, and sauces. They're full of vitamins and taste delicious whether they're eaten raw or cooked!",
    "Potatoes are tasty earth treasures that make delicious fries, mashed potatoes, and funny-shaped potato friends!",
    "Cauliflower is like a delicious white tree that grows in the garden, and it's perfect for making yummy cauliflower 'rice' or cheesy cauliflower bites!",
    "Radish is like a giant, white carrot that grows underground! It's crunchy and tasty, and you can eat it in salads or soups to make your meals extra yummy and healthy!",
    "Spinach is like magical green leaves that make you strong, just like Popeye! You can eat it in salads, sandwiches, or even in pasta, and it helps you grow big and strong like your favorite superheroes!",
    "Chili peppers are like fiery jewels in the garden, their vibrant colors and spicy flavors adding a kick to meals, teaching kids about different tastes and making cooking an exciting adventure!",
    "Cucumbers are like refreshing green gems, offering a crisp crunch and juicy flavor that makes them a perfect snack for kids, whether enjoyed plain or added to salads for a tasty treat.",
    "Eggplants are like purple superheroes in the garden, versatile and full of flavor, ready to be transformed into delicious dishes that kids will love, making mealtime an exciting culinary adventure!",
    "Garlic is like nature's flavor booster, adding a punch of savory goodness to dishes that kids will love, making meals taste extra delicious and satisfying with its aromatic charm!",
    "Onions are like flavorful building blocks in the kitchen, adding a delicious zing to meals that kids will enjoy, making dishes tastier and more exciting with their versatile crunch and aroma!",
    "Turnips are like nature's surprise packages, hiding under the soil until kids dig them up and discover their crunchy goodness, adding a fun twist to meals and turning cooking into a playful adventure!",
  ];
  static List<String> vegetablesAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> fruitsImages = [
    'assets/images/Fruits/apple.png',
    'assets/images/Fruits/banana.png',
    'assets/images/Fruits/orange.png',
    'assets/images/Fruits/trawberry.png',
    'assets/images/Fruits/grapes.png',
    'assets/images/Fruits/watermillon.png',
    'assets/images/Fruits/Kiwi.png',
    'assets/images/Fruits/Lemon.png',
    'assets/images/Fruits/Mango.png',
    'assets/images/Fruits/Peach.png',
    'assets/images/Fruits/Pineapple.png',
    'assets/images/Fruits/Plum.png',
  ];
  static List<String> fruitsNames = [
    'Apple',
    'Banana',
    'Orange',
    'Strawberry',
    'Grapes',
    'Watermelon',
    'Kiwi',
    'Lemon',
    'Mango',
    'Peach',
    'Pineapple',
    'Plum',
  ];
  static List<String> fruitsDetail = [
    "Apples are crunchy, juicy fruits that come in red, green, and yellow, and they're perfect for snacks, salads, or even making delicious apple juice!",
    "Bananas are like nature's yummy yellow candies, with a sweet and creamy taste perfect for adding to smoothies or baking delicious banana bread!",
    "Oranges are juicy, bright fruits that burst with tangy flavor and are filled with vitamin C, like a natural superhero juice box!",
    "Strawberries are like tiny red hearts bursting with sweetness and vitamin C! They're perfect for desserts, or even making delicious strawberry juice!",
    "Grapes are like little juicy balloons filled with sweet and refreshing flavors! They come in different colors like green, red, or purple, and they're perfect for enjoying on a sunny day!",
    "Watermelon is like a giant, juicy fruit filled with sweet, refreshing juice and lots of tiny black seeds! It's perfect for hot summer days, picnics, or just enjoying with friends and family!",
    "Kiwi is like a vibrant burst of tropical flavor, with its fuzzy brown skin hiding a sweet and tangy green flesh that kids will love to scoop up with a spoon, making snack time a juicy and refreshing delight!",
    "Lemons are like little balls of sunshine, their tangy juice adding a zesty kick to drinks and dishes, making snack time a fun and refreshing adventure for kids!",
    "Mangoes are like sunshine in a fruit, bursting with sweet, juicy flavor that kids will enjoy, turning every bite into a tropical adventure!",
    "Peaches are like summer's gift, with their soft, fuzzy skin and sweet, juicy insides, offering kids a delicious and refreshing treat that's perfect for sunny days!",
    "Pineapples are like tropical treasures, with their spiky outside and sweet, juicy inside, offering kids a delicious and refreshing treat!",
    "Plums are like little juicy gems, with their smooth, purple skin and sweet, flavorful flesh, offering kids a delicious and healthy treat!",
  ];
  static List<String> fruitsAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> kidsImages = [
    'assets/images/Kids/kid 6.png',
    'assets/images/Kids/kid 7.png',
    'assets/images/Kids/kid 8.png',
    'assets/images/Kids/kid 9.png',
    'assets/images/Kids/kid 10.png',
    'assets/images/Kids/kid 11.png',
  ];

}