class AllLists {

  static List<String> simpleAlphabetsAudios = [
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
  ];
  static List<String> simpleNumbersAudios = [
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
  ];
  static List<String> simpleUrduAudios = [
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/E.mp3',
    'assets/simpleAudios/A.mp3',
    'assets/simpleAudios/B.mp3',
    'assets/simpleAudios/C.mp3',
    'assets/simpleAudios/D.mp3',
    'assets/simpleAudios/E.mp3',
  ];
  static List<String> detailAlphabetsAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> detailNumbersAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
  ];
  static List<String> detailUrduAudios = [
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/A detail.mp3',
    'assets/detailAudios/B detail.mp3',
    'assets/detailAudios/C detail.mp3',
    'assets/detailAudios/D detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
    'assets/detailAudios/G detail.mp3',
    'assets/detailAudios/H detail.mp3',
    'assets/detailAudios/E detail.mp3',
    'assets/detailAudios/F detail.mp3',
  ];
  static List<String> allAlphabetsDetail = [
    'A is for Allah, who made everything and loves us all.',
    'B is for Bismillah, saying "In the name of Allah" before good things we do.',
    'C is for Charity, sharing with those who need our help.',
    'D is for Dua, talking to Allah and asking Him for what we need.',
    'E is for Eid, a happy time when Muslims celebrate together.',
    "F is for Fasting, when we don't eat or drink during Ramadan to feel closer to Allah.",
    'G is for Grand Mosque (Masjid al-Haram), the sacred mosque in Mecca that surrounds the Kaaba.',
    'H is for Halal, which means things that are okay for us to have or do in Islam.',
    'I is for Iman, having strong faith and belief in Allah.',
    'J is for Jannat, the beautiful garden in paradise where good people go.',
    'K is for Kaaba, the special building Muslims face during prayers.',
    'L is for Laylat al-Qadr, a very special night in Ramadan when the Quran was first sent down.',
    "M is for Muhammad, who taught us about Islam and is Allah's last prophet.",
    'N is for Night Prayer (Tahajjud), a special prayer Muslims can do at night.',
    'O is for One God (Tawheed), believing in and worshiping only Allah.',
    'P is for Peace (Salam), a greeting and feeling of kindness and harmony.',
    'Q is for Quran, the holy book of Islam that teaches us how to live.',
    'R is for Ramadan, a month of fasting, prayer, and reflection.',
    'S is for Salah, the prayers Muslims perform every day.',
    'T is for Tawakkul, trusting Allah and knowing He will take care of us.',
    'U is for Ummah, the worldwide community of Muslims who care for each other.',
    'V is for Virtue (Ihsan), striving to be the best version of ourselves in worship and behavior.',
    'W is for Wudu, washing before prayers to be clean and ready to worship.',
    'X is for Excellence in character, being kind, honest, and respectful like our Prophet Muhammad.',
    'Y is for Yaqeen: Unwavering faith and belief in Allah, His attributes, and His promises.',
    'Z is for Zakat, giving to those in need to help make the world a better place.',
  ];
  static List<String> allNumbersDetail = [
    "F is for Fasting, when we don't eat or drink during Ramadan to feel closer to Allah.",
    'G is for Hajj, a special journey Muslims take to the holy city of Mecca.',
    'H is for Halal, which means things that are okay for us to have or do in Islam.',
    'I is for Iman, having strong faith and belief in Allah.',
    'J is for Jannat, the beautiful garden in paradise where good people go.',
    'K is for Kaaba, the special building Muslims face during prayers.',
    'L is for Laylat al-Qadr, a very special night in Ramadan when the Quran was first sent down.',
    "M is for Muhammad, who taught us about Islam and is Allah's last prophet.",
    'N is for Night Prayer (Tahajjud), a special prayer Muslims can do at night.',
    'A is for Allah, who made everything and loves us all.',
    'B is for Bismillah, saying "In the name of Allah" before good things we do.',
    'C is for Charity, sharing with those who need our help.',
    'D is for Dua, talking to Allah and asking Him for what we need.',
    'E is for Eid, a happy time when Muslims celebrate together.',
    'O is for One God (Tawheed), believing in and worshiping only Allah.',
    'P is for Peace (Salam), a greeting and feeling of kindness and harmony.',
    'Q is for Quran, the holy book of Islam that teaches us how to live.',
    'R is for Ramadan, a month of fasting, prayer, and reflection.',
    'S is for Salah, the prayers Muslims perform every day.',
    'T is for Tawakkul, trusting Allah and knowing He will take care of us.',
  ];
  static List<String> allUrduDetail = [
    'V is for Virtue (Ihsan), striving to be the best version of ourselves in worship and behavior.',
    'W is for Wudu, washing before prayers to be clean and ready to worship.',
    'X is for Excellence in character, being kind, honest, and respectful like our Prophet Muhammad.',
    'Y is for Yaqeen: Unwavering faith and belief in Allah, His attributes, and His promises.',
    'Z is for Zakat, giving to those in need to help make the world a better place.',
    'A is for Allah, who made everything and loves us all.',
    'B is for Bismillah, saying "In the name of Allah" before good things we do.',
    'C is for Charity, sharing with those who need our help.',
    'D is for Dua, talking to Allah and asking Him for what we need.',
    'E is for Eid, a happy time when Muslims celebrate together.',
    "F is for Fasting, when we don't eat or drink during Ramadan to feel closer to Allah.",
    'G is for Hajj, a special journey Muslims take to the holy city of Mecca.',
    'H is for Halal, which means things that are okay for us to have or do in Islam.',
    'I is for Iman, having strong faith and belief in Allah.',
    'J is for Jannat, the beautiful garden in paradise where good people go.',
    'K is for Kaaba, the special building Muslims face during prayers.',
    'L is for Laylat al-Qadr, a very special night in Ramadan when the Quran was first sent down.',
    "M is for Muhammad, who taught us about Islam and is Allah's last prophet.",
    'N is for Night Prayer (Tahajjud), a special prayer Muslims can do at night.',
    'O is for One God (Tawheed), believing in and worshiping only Allah.',
    'P is for Peace (Salam), a greeting and feeling of kindness and harmony.',
    'Q is for Quran, the holy book of Islam that teaches us how to live.',
    'R is for Ramadan, a month of fasting, prayer, and reflection.',
    'S is for Salah, the prayers Muslims perform every day.',
    'T is for Tawakkul, trusting Allah and knowing He will take care of us.',
    'U is for Ummah, the worldwide community of Muslims who care for each other.',
    'V is for Virtue (Ihsan), striving to be the best version of ourselves in worship and behavior.',
    'W is for Wudu, washing before prayers to be clean and ready to worship.',
    'X is for Excellence in character, being kind, honest, and respectful like our Prophet Muhammad.',
    'Y is for Yaqeen: Unwavering faith and belief in Allah, His attributes, and His promises.',
    'Z is for Zakat, giving to those in need to help make the world a better place.',
    'O is for One God (Tawheed), believing in and worshiping only Allah.',
    'P is for Peace (Salam), a greeting and feeling of kindness and harmony.',
    'Q is for Quran, the holy book of Islam that teaches us how to live.',
    'R is for Ramadan, a month of fasting, prayer, and reflection.',
    'S is for Salah, the prayers Muslims perform every day.',
    'T is for Tawakkul, trusting Allah and knowing He will take care of us.',
    'U is for Ummah, the worldwide community of Muslims who care for each other.',
  ];
  static List<String> alphabetsImages = [
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
  ];
  static List<String> numbersImages = [
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
  ];
  static List<String> urduImages = [
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
    'assets/images/Alphabets/A detail.png',
  ];
  static List<String> shapes = [
    'assets/images/Shapes/Circle.png',
    'assets/images/Shapes/Triangle.png',
    'assets/images/Shapes/Square.png',
    'assets/images/Shapes/Pentagon.png',
    'assets/images/Shapes/Hexagon.png',
    'assets/images/Shapes/Polygon.png',
  ];
  static List<String> animals = [
    'assets/images/animals/Tiger.png',
    'assets/images/animals/lion.png',
    'assets/images/animals/Deer.png',
    'assets/images/animals/Elephant.png',
    'assets/images/animals/Panda.png',
    'assets/images/animals/Zebra.png',
  ];
  static List<String> trees = [
    'assets/images/Trees/Oak Tree.png',
    'assets/images/Trees/Maple Tree.png',
    'assets/images/Trees/Pine Tree.png',
    'assets/images/Trees/Cherry Tree.png',
    'assets/images/Trees/Palm Tree.png',
    'assets/images/Trees/Apple tree.png',
  ];
  static List<String> colors = [
    'assets/images/Shapes/Circle.png',
    'assets/images/Shapes/Triangle.png',
    'assets/images/Shapes/Square.png',
    'assets/images/Shapes/Pentagon.png',
    'assets/images/Shapes/Hexagon.png',
    'assets/images/Shapes/Polygon.png',
  ];
  static List<String> vegetables = [
    'assets/images/Trees/Oak Tree.png',
    'assets/images/Trees/Maple Tree.png',
    'assets/images/Trees/Pine Tree.png',
    'assets/images/Trees/Cherry Tree.png',
    'assets/images/Trees/Palm Tree.png',
    'assets/images/Trees/Apple tree.png',
  ];
  static List<String> fruits = [
    'assets/images/Trees/Oak Tree.png',
    'assets/images/Trees/Maple Tree.png',
    'assets/images/Trees/Pine Tree.png',
    'assets/images/Trees/Cherry Tree.png',
    'assets/images/Trees/Palm Tree.png',
    'assets/images/Trees/Apple tree.png',
  ];

}